Conglomerate of Create methods
Sparkling-Barracudas/Main-Project pull request #11
Opened 2022-03-09 20:32 UTC by ajminer0913

2022-03-10 15:16 UTC, Matthew-Bustamante requested changes
Overall looks good and everything works the way its suppose to.  I tested the validity of input statements and they do prevent words and letters from being entered but they do not prevent negative numbers from being entered.  This can be implemented later on but I just wanted to bring that to your attention.  Just make these simple changes and I'll approve.

2022-03-10 15:16 UTC, Matthew-Bustamante commented on Create.java
> +import java.sql.Connection;
Don't need this on line 4

2022-03-10 15:16 UTC, Matthew-Bustamante commented on Create.java
> +import java.sql.ResultSet;
Don't need this either on line 5

2022-03-10 15:16 UTC, Matthew-Bustamante commented on Create.java
> +
Need to import scanner.  I ran this on my machine and there was an error because there was no scanner

2022-03-12 01:22 UTC, Matthew-Bustamante commented
Disregard the previous comment, Nathan will make the minor changes.

2022-03-12 01:22 UTC, Matthew-Bustamante approved these changes
Disregard the previous comment, Nathan will make the minor changes. Forgot to approve

2022-03-13 23:26 UTC, nkauffm1 approved these changes
Besides the minor changes it looks good. I will make those changes and submit a pull request with those changes.

2022-03-13 23:26 UTC, merged